INSERT INTO TBL_COUNTRY (name) VALUES ('China');
INSERT INTO TBL_COUNTRY (name) VALUES ('India');
INSERT INTO TBL_COUNTRY (name) VALUES ('Brazil');
INSERT INTO TBL_COUNTRY (name) VALUES ('USA');
INSERT INTO TBL_COUNTRY (name) VALUES ('Italy');
INSERT INTO TBL_COUNTRY (name) VALUES ('Iran');
INSERT INTO TBL_COUNTRY (name) VALUES ('Japan');
INSERT INTO TBL_COUNTRY (name) VALUES ('Germany');