INSERT INTO TBL_CAR (name) VALUES ('BMV');
INSERT INTO TBL_CAR (name) VALUES ('BENZ');
INSERT INTO TBL_CAR (name) VALUES ('HONDA');
INSERT INTO TBL_CAR (name) VALUES ('TOYOTA');
INSERT INTO TBL_CAR (name) VALUES ('CADILLAC');
INSERT INTO TBL_CAR (name) VALUES ('CHEVROLET');
